### ISSUE TITLE
Please add NULL-Safty support.

### ISSUE THREAD

**Issue by DarkHeros09** [mahdizakizadeh/shifting_tabbar#5]
Hi 
Thank you for creating this package, can you please update your package to support null-safety.

**Comment by mzakizadeh** [comment]
Hello @DarkHeros09 
Thanks for using this package. Null-safety is now supported 😁
Update your `pubspec.yaml` to new version:
```yaml
dependencies:
    ...
    shifting_tabbar: ^1.0.0
```
